<?php require(__DIR__ . '/../base.html') ?>
<table class="easyui-datagrid" id="dg" url="/user/users" style="width:520px;height:250px">
    <thead>
    <tr>
        <th field="id" width="100">ID</th>
        <th field="username" width="200">User Name</th>
        <th field="email" width="200">Email</th>
    </tr>
    </thead>
</table>
<div id="toolbar">
    <a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="createUser()">New User</a>
    <a href="#" class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="editUser()">Edit User</a>
    <a href="#" class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="deleteUser()">Remove User</a>
</div>

<div id="dlg" class="easyui-dialog" style="width:400px;height: 200px;padding: 10px 20px;" closed="true"
     buttons="#dlg-buttons">
    <div class="ftitle">User Information</div>
    <form id="fm" method="post">
        <div class="fitem">
            <label>User Name:</label>
            <input name="username" class="easyui-validatebox" required="true">
        </div>
        <div class="fitem">
            <label>Email:</label>
            <input name="email" class="easyui-validatebox" validType="email">
        </div>
    </form>
</div>

<div id="dlg-buttons">
    <a href="#" class="easyui-linkbutton" iconCls="icon-ok" onclick="saveUser()">Save</a>
    <a href="#" class="easyui-linkbutton" iconCls="icon-cancel"
       onclick="javascript:$('#dlg').dialog('close')">Cancel</a>
</div>

<script>
    // show dialog to create user
    function createUser() {
        $("#dlg").dialog('open').dialog('setTitle', 'New User');
        $("#fm").form('clear');
        url = "/user/create";
    }

    // show dialog to edit user
    function editUser() {
        // get selected user record
        var row = $('#dg').datagrid('getSelected');
        if (row) {
            $("#dlg").dialog('open').dialog('setTitle', 'Edit User');
            $("#fm").form('load', row);
            url = '/user/save?id=' + row.id;
        }
    }

    function saveUser() {
        $("#fm").form('submit', {
            url: url,
            onSubmit: function () {
                return $(this).form('validate');
            },
            success: function (result) {
                result = eval('(' + result + ')');
                if (result.errorMsg) {
                    $.messager.show({
                        title: 'Error',
                        msg: result.errorMsg
                    })
                } else {
                    $("#dlg").dialog('close');
                    $("#dg").datagrid('reload');
                }
            }
        });
    }

    function deleteUser() {
        var row = $('#dg').datagrid('getSelected');
        if (row) {
            $.messager.confirm('Confirm', 'Are you sure you want to destroy this user?', function (r) {
                if (r) {
                    $.post('/user/delete', {id: row.id}, function (result) {
                        if (result.status) {
                            $('#dg').datagrid('reload');	// reload the user data
                        } else {
                            $.messager.show({	// show error message
                                title: 'Error',
                                msg: result.errorMsg
                            });
                        }
                    }, 'json');
                }
            });
        }
    }
</script>