<?php

class GlobalPlugin extends Yaf_Plugin_Abstract
{
    public function routerShutdown(Yaf_Request_Abstract $request, Yaf_Response_Abstract $response)
    {
//        var_dump("Router Shutdown!", $request);
//        exit();
        // TODO: check if the user is authenticated?
        if (false) {
            // if not, redirect to the 'login' page
            $this->_login_required($request);
        }
        parent::routerShutdown($request, $response); // TODO: Change the autogenerated stub
    }

    /**
     * Redirect to the 'login' page
     * @param Yaf_Request_Abstract $request
     */
    private function _login_required(Yaf_Request_Abstract $request)
    {
        $request->setControllerName('Auth');
        $request->setActionName('login');
    }

    /**
     * 处理请求前判断
     * @param Yaf_Request_Abstract $request
     * @param Yaf_Response_Abstract $response
     * @return mixed
     */
    public function preDispatch(Yaf_Request_Abstract $request, Yaf_Response_Abstract $response)
    {
        // 如果是Ajax请求，关闭view
        if ($request->isXmlHttpRequest()) {
            disable_view();
        }
        parent::preDispatch($request, $response); // TODO: Change the autogenerated stub
    }
}