<?php

class GlobalPlugin extends Yaf_Plugin_Abstract
{
    public function routerShutdown(Yaf_Request_Abstract $request, Yaf_Response_Abstract $response)
    {
//        var_dump("Router Shutdown!", $request);
//        exit();
        // TODO: check if the user is authenticated?
        if(false){
            // if not, redirect to the 'login' page
            $this->_login_required($request);
        }
        parent::routerShutdown($request, $response); // TODO: Change the autogenerated stub
    }

    /**
     * Redirect to the 'login' page
     * @param Yaf_Request_Abstract $request
     */
    private function _login_required(Yaf_Request_Abstract $request){
        $request->setControllerName('Auth');
        $request->setActionName('login');
    }
}