<?php

class GlobalPlugin extends Yaf_Plugin_Abstract
{
    public function routerStartup(Yaf_Request_Abstract $request, Yaf_Response_Abstract $response)
    {
//        var_dump("Router Started!", $request);
//        exit();
        parent::routerStartup($request, $response); // TODO: Change the autogenerated stub
    }
}